name: C++ build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [serial, parallel]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ build environment
      uses: marketplace/actions/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}

    - name: Build serial/parallel executable
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}-g++
        make

    - name: Run C++ program with serial/parallel executable
      run: |
        cd build
        ./program
