name: Build and Run C++ Program

on: [push]

jobs:
  build:
    name: Elliptic mesh generator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install g++ -y
    - name: Build
      run: g++ -o myprogram EllipticMeshGenerator.cpp
    - name: Run
      run: ./myprogram

